version: "3.8"

services:
  db:
    image: mysql:5.7.35
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - "nfsvolume:/var/lib/mysql"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_PASSWORD: "root"
    networks:
      first-cluster:
        aliases:
          - db
    healthcheck:
      test: mysqladmin ping -h localhost -u root --password=$$MYSQL_PASSWORD
      timeout: 20s
      retries: 10
    deploy:
      placement:
        constraints: [node.role == worker]

  app:
    build:
      context: ./app
    image: app:1
    ports:
      - 80:5000
    command: bash /wait-for.sh db:3306 -- python app.py
    depends_on:
      - db
    networks:
      - first-cluster
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/healthy"]
      interval: 20s
      timeout: 2s
      retries: 3
      start_period: 5s
    restart: on-failure
    deploy:
      mode: replcated
      replicas: 3
      resources:
        limits:
          cpus: "0.25"
          memory: 100M
        reservations:
          cpus: "0.2"
          memory: 50M
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
        update_config:
          parallelism: 1
          delay: 10s
          failure_action: continue
          monitor: 60s
          max_failure_ratio: 0.3

networks:
  first-cluster:
    driver: "overlay"
    attachable: true

volumes:
  nfsvolume:
    driver: "local"
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.105,rw,nfsvers=4,sync"
      device: ":/mnt/nfs_share/mysql"
